### ISSUE TITLE
Segmentation fault in Fedora 39

### ISSUE THREAD

**Issue by BoukeHaarsma23** [libretiny-eu/ltchiptool#17]
Hi, thanks for your hard work. It is appreciated.

I am wanting to flash a module using my linux laptop. But I am hitting an assertion here.

```
[bouke@Slimbook ~]$ ltchiptool -vvv gui
22:31:53: Debug: Adding duplicate image handler for 'Windows bitmap file'
22:31:53: Debug: Adding duplicate animation handler for '1' type
22:31:53: Debug: Adding duplicate animation handler for '2' type
D: Found Local data snapshot (v1.4.1) - /home/bouke/.local/lib/python3.12/site-packages/ltchiptool
D: Using v1.4.1 (/home/bouke/.local/lib/python3.12/site-packages/ltchiptool) as default
D: Using selector: EpollSelector

(ltchiptool:58704): Gtk-CRITICAL **: 22:31:53.843: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
D: Started DeviceWatcher
Segmentation fault (core dumped)
```

Using Fedora 39 and using all pypi packages. The GUI first starts normally, but gets this segmentation fault when switching tabs.
Using v4.10.1

Would appreciate if you could take a look. (As a suggestion maybe consider a flatpak in the future?)

**Comment by alufers** [comment]
I am also getting those crashes, the ` gtk_box_gadget_distribute: assertion 'size >= 0' failed ` line seems to be bogus, the segfaults happen in different places in the code.

I think the cause of these crashes is the fact that ltchiptool does GUI operations from multiple threads, which GTK does not like (this might also be the cause of macOS crashes).

I quickly added this piece code to a few places:

```py
import threading
print("PluginsPanel.__init__, get_native_id=", threading.get_native_id())
```

And from the logs I can see that OnWorkStopped is called from a different thread (and it also manipulates the GUI):

```
PluginsPanel.__init__, get_native_id= 307888
StartWork get_native_id= 307888
PluginsPanel.OnWorkStopped, get_native_id= 307943
```

**Comment by kuba2k2** [comment]
Good point. That might have been not an issue on Windows, and since I'm developing on Windows I never noticed such things - all this is actually my first go at wxPython and GUI apps.

It should be possible to convert these worker thread callbacks so that they execute on main thread. I think something similar has been implemented in another class already; I'm not sure where exactly.

Something similar has been implemented here:
https://github.com/tuya-cloudcutter/cloudcutter-universal/blob/master/cloudcutter/modules/base/event.py
but that relies on AsyncIO for the entire project.

**Comment by kuba2k2** [comment]
Hi, this got closed automatically. If you can, let me know if the issue is solved (at least partially). Clicking on the Plugins tab is still a known issue on Linux.

**Comment by sandervankasteel** [comment]
@kuba2k2 unfortunately on Arch Linux (I've tried with Python 3.13 and 3.10), I still get segfaults. 😔

**Comment by mathmakgakpak** [comment]
I get bogus core dumped crashes on manjaro (arch based) too.
And running under wine, ltchiptool fails to detect any com ports.
BUT running under virtualbox with the tty(USB) device mapped using `device host` mode, works. Didn't test how well it works but it can recognize the chip atleast (read device info).

Also it is possible to use https://github.com/openshwprojects/BK7231GUIFlashTool that is ran using bottles (wine),
Though you need to map com port to a correct tty device (https://gitlab.winehq.org/wine/wine/-/wikis/Wine-User%27s-Guide#serial-and-parallel-ports ).
Also i needed to change uart timeouts
<img width="539" height="196" alt="Image" src="https://github.com/user-attachments/assets/8635654c-4b46-4678-af63-b4814d25fd45" />
then i could successfully write the openbeken firmware.

**Comment by kuba2k2** [comment]
Use the ltchiptool CLI instead if you're on Linux. The GUI doesn't work well on Linux.

**Comment by mathmakgakpak** [comment]
okay thanks!
