### ISSUE TITLE
malware detected ??

### ISSUE THREAD

**Issue by phil31** [libretiny-eu/ltchiptool#20]
hi,

i juste download the exe 4.10.1

and scan the file .. 

![image](https://github.com/libretiny-eu/ltchiptool/assets/9626218/05f11aec-6972-4742-a4d2-f13eade0d4e4)

![image](https://github.com/libretiny-eu/ltchiptool/assets/9626218/6801c101-7f1a-41b5-8f28-1bd81304d2ef)

what's wrong ?

**Comment by kuba2k2** [comment]
See #10.

**Comment by phil31** [comment]
ok 
thanks !
