### ISSUE TITLE
ltchiptool-v4.11.1.exe triggers MCAfee Virus threat ti!EBCF3BF55DBF - 4.11.0 does not trigger

### ISSUE THREAD

**Issue by hcjehg** [libretiny-eu/ltchiptool#27]
ltchiptool-v4.11.1.exe triggers MCAfee Virus threat ti!EBCF3BF55DBF

No problems with  ltchiptool-v4.11.0.exe

**Comment by kuba2k2** [comment]
See #10. TL;DR: antivirus false-positives are just random. If you're worried about your PC getting infected, please use the Python version (`pip install ltchiptool[gui]`).
