### ISSUE TITLE
Microsoft Defender detects trojan in newest Release

### ISSUE THREAD

**Issue by panzerknacker20111** [libretiny-eu/ltchiptool#8]
Hello,

I wanted to try your newest release, but my Microsoft Defender immediatly raised an alarm and deleted the downloadet file.

It shows the following:

![image](https://github.com/libretiny-eu/ltchiptool/assets/53277885/1732a88e-2fbc-407d-8dc1-6fd656b5deab)

The previous Release download shows no problems at all.

Just wanted to make you aware of this. Maybe it is false positive but maybe not. I will always trust defender first ;)

**Comment by sincze** [comment]
Same here indeed:
![image](https://github.com/libretiny-eu/ltchiptool/assets/5776333/21a669b0-a2c5-4851-9f16-5f9a0624b972)

**Comment by kuba2k2** [comment]
I tried to exclude various modules and revert the code, but sadly I got the same results.

The only advice for now is to either ignore the virus alerts (false positives), or install ltchiptool using Python via `pip install ltchiptool`.

**Comment by panzerknacker20111** [comment]
I tested the new 4.4.1 release and defender had nothing to complain. great. Thank you for your work. This issue is resolved with that release I think.
